---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	LLM_assistant(LLM_assistant)
	tool_node(tool_node)
	final_response_node(final_response_node)
	__end__([<p>__end__</p>]):::last
	LLM_assistant -.-> final_response_node;
	LLM_assistant -.-> tool_node;
	__start__ --> LLM_assistant;
	tool_node --> LLM_assistant;
	final_response_node --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
